baseURL = "/"
languageCode = "en-us"
title = "My New Hugo Site"

[permalinks]
  articles = "/:section/:title/"
  page = "/:title/"

[build]
  command = "hugo"
  publish = "public"

[context.production.environment]
  HUGO_VERSION = "0.52"
  HUGO_ENV = "production"
